title: "PHPMemo"
description: "Шпаргалки и заметки по PHP и веб-разработке"
baseurl: "/phpmemo" 
url: "https://vanyazaov.github.io"

# Настройки для Jekyll
theme: minima
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false
  input: GFM # GitHub Flavored Markdown

# Объявляем кастомные коллекции
collections:
  notes:
    output: true
    permalink: /notes/:path/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
 
