title: "PHPMemo"
description: "Шпаргалки и заметки по PHP и веб-разработке"
baseurl: "/phpmemo" 
url: "https://vanyazaov.github.io"

# Настройки для Jekyll
theme: minima
# Объявляем кастомные коллекции
collections:
  notes:
    output: true
    permalink: /notes/:path/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
version: {% raw %}{{ site.time | date: '%Y%m%d%H%M' }}{% endraw %}
