# Объявляем кастомные коллекции
collections:
  notes:
    output: true   # Важно: это разрешает Jekyll создавать отдельные страницы для каждого файла в коллекции
    permalink: /notes/:path/   # Вот это ключевая строка! # Опционально: настраивает URL для страниц записей
  
